import Head from 'next/head'
import Image from 'next/image'
import { Heading, Button } from './components'
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <div className={styles.overlay}>
            <section className={styles.hero}>
              <Heading />
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}
